import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Analytics } from '@vercel/analytics/next';
// components
import { Header } from '@/widgets/header/Header';
import { Footer } from '@/widgets/footer/Footer';
import { OverlayProvider } from '@/app/providers/OverlayProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <OverlayProvider>
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1 mb-8">
              {children}
              <Analytics />
            </main>
            <Footer />
          </div>
        </OverlayProvider>
      </body>
    </html>
  );
}
